import sys
sys.path.append("/eisoo/CZB-Test/workspace/")
import yaml
import pytest
import allure
from urllib import parse
from common import common
import requests
from time import sleep
from requests.packages.urllib3.exceptions import InsecureRequestWarning
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

@allure.title("发起vmware增量备份任务成功！")
@pytest.mark.parametrize("jobinfo, expected",
                         [
                             ({"jobBackupType": 2,
                               "jobDesc": "",
                               "jobStatus": 4},"success"),
                         ])
def test_Runjob(login_operator, get_baseurl, get_version, get_vmwareip, jobinfo, expected):
    file = open('/eisoo/CZB-Test/workspace/6-0-Post_Upgrade_Validation/TestData/config.yaml')
    res = yaml.load(file, Loader=yaml.FullLoader)
    base_url = get_baseurl
    version = get_version
    jobId = common.jobId_from_jobName(base_url, version, login_operator, 'vmware')

    url = parse.urljoin(base_url, res['runjob_url']).format(jobId)
    referer = parse.urljoin(base_url, res['runjob_referer'])
    method = res['runjob_method']

    if get_vmwareip == False:
        pytest.skip(msg='This test if only for file backup')
    elif version in ('7.0.8.0', '7.0.9.1', '7.0.10.0', '7.0.11.0'):
        cookie, userId = login_operator
        header = {"referer": "%s" % (referer)}
    else:
        cookie, userId, csrftoken = login_operator
        header = {"referer": "%s" % (referer),
                  "x-csrftoken": "%s" % (csrftoken)}
    jobinfo['jobId'] = jobId
    print(url)
    print(jobinfo)
    print(header)
    print(cookie)

    s = common.Webrequests()
    response = s.run_main(method, url, jobinfo, header, cookie)
    print(response)
    assert response['status'] == expected
    sleep(30)

@allure.title("恢复oracle备份任务成功!")
@pytest.mark.parametrize("jobinfo, expected",
                         [
                             ({"engineType": 1002,
                               "jobAsResource": {},
                               "jobDataProduceType": 1,
                               "jobDesc": "",
                               "jobStorageId": "1",
                               "jobType": "eso_backupengine_vmwareengine"}, "success")
                         ])
def test_RunRestore(login_operator, login_sadmin, get_baseurl, get_version, get_vmwareip, cluster_idSet, platform_details_from_IP, get_Builtin_Client_Id, jobinfo, expected):
    file = open('/eisoo/CZB-Test/workspace/6-0-Post_Upgrade_Validation/TestData/config.yaml')
    res = yaml.load(file, Loader=yaml.FullLoader)
    base_url = get_baseurl
    version = get_version
    clientIP = get_vmwareip
    
    url = parse.urljoin(base_url, res['restore_job_url'])
    referer = parse.urljoin(base_url, res['restore_job_referer'])
    method = res['restore_job_method']

    if clientIP == False:
        pytest.skip(msg='This test if only for file restore')
    elif version in ('7.0.8.0', '7.0.9.1', '7.0.10.0', '7.0.11.0'):
        cookie, userId = login_operator
        header = {"referer": "%s" % (referer)}
    else:
        cookie, userId, csrftoken = login_operator
        header = {"referer": "%s" % (referer),
                  "x-csrftoken": "%s" % (csrftoken)}
    
    clusterId, vip = cluster_idSet
    tuc, BackupType, timestamp = common.get_last_timepoint(login_operator, base_url, version, cluster_idSet, 'aaa')
    timepoint = common.timestamptopoint(login_operator, base_url, version, cluster_idSet, 'aaa')
    gnsPath, dpName, num = common.get_vmwaretimepoint_subset(login_operator, base_url, version, cluster_idSet, 'aaa')
    jobVplatformIP, jobVplatformName, jobVplatformId, version = platform_details_from_IP
    jobId = common.jobId_from_jobName(base_url, version, login_operator, 'aaa')
    restore_jobName = common.get_restore_jobname(login_operator, base_url, version, 'aaa')

    jobinfo['clusterId'] = "%s" %clusterId
    jobinfo['clusterVip'] = "%s" %vip
    jobinfo['jobClientId'] = "%s" %get_Builtin_Client_Id
    jobinfo['jobCreatorId'] =  "%s" %userId
    jobinfo['jobDestClientId'] = "%s" %get_Builtin_Client_Id
    jobinfo['jobId'] = "%s" %jobId
    jobinfo['jobRelatedId'] = "%s" %jobId
    jobinfo['jobName'] = "%s" %restore_jobName
    jobinfo['jobVplatformId'] = "%s" %jobVplatformId
    jobinfo['jobVplatformIp'] = "%s" %jobVplatformIP
    jobinfo['jobVplatformName'] = "%s" %jobVplatformName

    dispPath = '[' + '"' + "%s" %timepoint + '"' 
    i = num
    j = 0
    while i >= 0:
        dispPath = dispPath + "," + '"' + dpName[j] + '"'
        j += 1
        i -= 1
    dispPath = dispPath + ']'
    restore_config = {"vmgns":"%s" %gnsPath,
                      "afterStart": "false",
                      "afterDel": "true",
                      "autogeneratedMac": "false",
                      "nameSuffix":"",
                      "newName":"",
                      "disks":[],
                      "vifs":[]}
    jobinfo['jobDataSource'] = [{"customer": "%s" %dpName[num],
                                 "dispPath": "%s" %dispPath,
                                 "fullPath": "%s" %gnsPath}]
    jobinfo['jobAdvParam'] = [{"key": "EEE_RESTORE_GNS", "value": "%s" %(gnsPath)},
                              {"key": "EEE_IS_MOUNT_RESTORE", "value": "0"},
                              {"key": "EEE_TIMEPOINT_USER_CHOOSE", "value": "%s" %(tuc)},
                              {"key": "EEE_RESTORE_USEORIGN", "value": "1"},
                              {"key": "EEE_IS_USE_THREAD", "value": "1"},
                              {"key": "EEE_USE_THREAD_NUM", "value": "2"},
                              {"key": "EEE_RESTORE_TRANSPORTMODE", "value": "nbd"},
                              {"key": "EEE_JOB_RUN_IMMEDIATELY", "value": "1"},
                              {"key": "EEE_RESTORE_CONFIG", "value": "%s" %(restore_config)}]
    
    print(url)
    print(f'jobinfo:{jobinfo}')
    print(header)
    print(cookie)

    s = common.Webrequests()
    response = s.run_main(method, url, jobinfo, header, cookie)
    print(response)
    assert response['status'] == expected
    sleep(20)

if __name__== '___main__':
    pytest.main(["test_01_filejob.py --Console_URL=base_url --Version=version --vmware_tIP=clientIP"])
